[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "rabota2"
version = "0.1.0"
description = "Web novel planner"
requires-python = ">=3.10"
dependencies = [
    "PySide6",
    "blurwindow",
    "bump2version",
]
